services:
  db:
    image: mysql:8.0
    container_name: todo-db
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      # ホスト側の ./db/data をコンテナのデータ領域に同期
      - ./db/data:/var/lib/mysql
      # ホスト側の ./db/init をコンテナの初期化スクリプト領域に同期
      - ./db/init:/docker-entrypoint-initdb.d

  app:
    build: ./app
    container_name: todo-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db